_target_: src.model.detector.NOCTIS
log_interval: 5
log_dir: ${save_dir}
segmentor_width_size: 640                     # make it stable
descriptor_width_size: 640

defaults:
  - segmentor_model: grounded_sam
  - descriptor_model: dinov2

post_processing_config:
  mask_post_processing:
    min_box_size: 0.05                        # relative to image size
    min_mask_size: 3e-4                       # relative to image size
  nms_threshold: 0.25

matching_config:
  semantic_score_weight_factor: 1
  semantic_aggregation_function: avg_5
  semantic_confidence_threshold: 0.2

  appearance_score_weight_factor: 1
  appearance_confidence_threshold: 0 #0.5
  appearance_cycle_threshold: 5
  appearance_aggregation_function: max
  appearance_score_extra_weight_factor: 2

  use_detector_confidence: True
  final_confidence_threshold: 0.2
  max_num_instances: 100                      # max number of instances to consider, 100 is used in BOP toolkit

onboarding_config:
  rendering_type: "templates"                 # or pbr (or onboarding_static or onboarding_dynamic for model-free)
  reset_descriptors: False
  level_templates: 0                          # 0 is coarse, 1 is medium, 2 is dense

storage_device: "cpu"
skip_inference: False
save_mask: True
save_score_distribution: False
return_detections: False
name_prediction_file:
